version: "3.8"
services:
  pwn-baby-bof:
    build:
      context: .
      args: 
        FLAG: "utflag{can_we_pretend_that_airplanes}"
        USER: "babybof"
    deploy:
      replicas: 1
    ports:
      - "5013:9000"
    read_only: true
