version: "3.8"
services:
  pwn-overflow:
    build:
      context: .
      args: 
        FLAG: "utflag{thank_for_fixing_stream}"
        USER: "alice"
    deploy:
      replicas: 1
    ports:
      - "31337:9000"
    read_only: true
