version: "3.8"
services:
  nc_complex_hello:
    build:
      context: .
      args:
        FLAG: "utflag{not_enough_math_apparently}"
        READ_TIMEOUT: "300"
        APP_USER: "appuser"
        MINIMUM_QUESTIONS: "256"
        MAXIMUM_QUESTIONS: "512"
        LISTEN_PORT: "5000"
        BIN_NAME: "nc_complex_hello"
    deploy:
      replicas: 1
    ports:
      - "5421:5000"
    read_only: true
