version: "3.8"
services:
  pwn-basics:
    build:
      context: .
      args: 
        FLAG: "utflag{jump_jump_jumop3240}"
        USER: "basics"
    deploy:
      resources:
        limits:
          cpus: '.1'
          memory: 150M
    ports:
      - "5500:9000"
    read_only: true
