version: "3.8"
services:
  pwn-overflow:
    build:
      context: .
      args: 
        FLAG: "utflag{struct_on_da_stack}"
        USER: "overflow"
    deploy:
      replicas: 1
    ports:
      - "9005:9000"
    read_only: true
