version: "3.8"
services:
  reversing-qjs:
    build:
      context: .
      args: 
        FLAG: "utflag{quickjs_more_like_slow_js}"
        USER: "qjs"
    deploy:
      replicas: 1
    ports:
      - "4250:9000"
    read_only: true
