version: "3.8"
services:
  pwn-overflow:
    build:
      context: .
      args: 
        FLAG: "utflag{lol_wait_ur_not_huck}"
        USER: "int"
    deploy:
      replicas: 1
    ports:
      - "9001:9000"
    read_only: true
