version: "3.8"
services:
  rev-bomb:
    build:
      context: .
      args: 
        FLAG: "utflag{BOOM!!!!}"
        USER: "bomb"
    deploy:
      replicas: 1
    ports:
      - "9001:9000"
    read_only: true
