version: "3.8"
services:
  pwn-rop:
    build:
      context: .
      args: 
        FLAG: "utflag{beep_boop}"
        USER: "rop"
    deploy:
      replicas: 1
    ports:
      - "9003:9000"
    read_only: true
    
