version: "3.8"
services:
  pwn-salesman:
    build:
      context: .
      args: 
        FLAG: "utflag{get_got_get_got9813}"
        USER: "salesman"
    deploy:
      resources:
        limits:
          cpus: .1
          memory: 150M
    ports:
      - "5501:9000"
    read_only: true
