version: "3.8"
services:
  nc_simple_hello:
    build:
      context: .
      args:
        FLAG: "utflag{tcp_s3rvers_are_the_best}"
        APP_USER: "appuser"
        LISTEN_PORT: "5000"
        BIN_NAME: "nc_simple_hello"
    deploy:
      replicas: 1
    ports:
      - "5421:5000"
    read_only: true
